FROM eclipse-temurin:17-jdk-jammy as base
WORKDIR ././.
RUN ./mvnw dependency:resolve

FROM base as development
CMD [ "./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=mysql", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000'" ]

FROM base as build
RUN ./mvnw package

FROM eclipse-temurin:17-jre-jammy as production
EXPOSE 8080
COPY --from=build /app/target/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", ".jar"]