export const ADD_INGR = 'ADD_INGR';
export const REMOVE_INGR = 'REMOVE_INGR';
export const SET_INGR = 'SET_INGR';
export const FETCH_FAILIURE = 'FETCH_FAILIURE';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILIURE = 'AUTH_FAILIURE';
export const AUTH_STATUS = 'AUTH_STATUS';
export const AUTH_TIME = 'AUTH_TIME';
export const AUTH_LOGOUT= 'AUTH_LOGOUT';

export const DB_CONNECTION = 'DB_CONNECTION';
export const DB_STATUS= 'DB_STATUS';
export const DB_DATA = 'DB_DATA';
export const DB_USER = 'DB_USER';
export const DB_PASSWORD = 'DB_PASSWORD';
export const DB_FETCH_USER_DATA_START = 'DB_FETCH_USER_DATA_START';
export const DB_FETCH_USER_DATA_SUCCESS = 'DB_FETCH_USER_DATA_SUCCESS';
export const DB_FETCH_USER_DATA_FAILIURE = 'DB_FETCH_USER_DATA_FAILIURE';

export const BUY_BURGER_INIT = 'BUY_BURGER_INIT';
export const BUY_BURGER_START = 'BUY_BURGER_START';
export const BUY_BURGER_FAILIURE = 'BUY_BURGER_FAILIURE';
export const BUY_BURGER_SUCCESS = 'BUY_BURGER_SUCCESS';

export const AUTH_REDIRECT = 'AUTH_REDIRECT';