export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

/////////////Data.userData managment

export const SET_USER_DATA = 'SET_USER_DATA';
export const GET_USER_DATA = 'GET_USER_DATE'
export const FAILED_USER_DATA = 'FAILED_USER_DATA'
export const USER_DATA = 'USER_DATA'
export const ADD_ORDER_TO_USER_DB = 'ADD_ORDER_TO_USER_DB'
//////////////Data.activeData managment

export const ACTIVE_DATA = 'ACTIVE_DATA'
export const SET_ACTIVE_DATA = 'SET_ACTIVE_DATA'
export const GET_ACTIVE_DATA = 'GET_ACTIVE_DATA'
export const UPDATE_ACTIVE_DATA = 'UPDATE_ACTIVE_DATA'
export const CHECK_ACTIVE_DATA = 'CHECK_ACTIVE_DATA'
