export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const USER_DATA_FETCH = "USER_DATA_FETCH";
export const USER_DATA_INIT = "USER_DATA_INIT";
export const USER_DATA_GET = "USER_DATA_GET";
export const USER_DATA_SET = "USER_DATA_SET";

export const USER_ORDRES_LOAD = "USER_ORDERS_LOAD";
export const USER_ORDRES_LOAD_SUCCESS = "USER_ORDERS_LOAD_SUCCESS";
export const USER_ORDRES_LOAD_FAILIURE = "USER_ORDERS_LOAD_FAILIURE";
export const USER_ORDERS_GET = "USER_ORDERS_GET";
export const USER_ORDERS_ADD = "USER_ORDERS_ADD";
export const USER_ORDERS_ADD_SUCCESS = "USER_ORDERS_ADD_SUCCESS";
export const USER_ORDERS_ADD_FAILIURE = "USER_ORDERS_ADD_FAILIURE";