#Each item's cost is expressed in cents (1$ = 100)
# Acceptible ingridients are: bun, patty, tomato, lettuce, onions, pickles, bacon
# Acceptible souces are: tomato, mayo, bbq, curry
Price: 
  default:
    bun: 50
    patty: 150
    tomato: 50
    lettuce: 50
    onions: 100
    pickles: 150
    souce:
      tomato: 20
      mayo: 30
      bbq: 40
      curry: 80
  premium:
    bun: 100
    patty: 300
    tomato: 100
    lettuce: 100
    onions: 200
    pickles: 400
    bacon: 200
    souce:
      tomato: 50
      mayo: 80
      bbq: 90
      curry: 190